// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsotemfxtwmjgpvjdatz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzb3RlbWZ4dHdtamdwdmpkYXR6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEwMzcxNDMsImV4cCI6MjA1NjYxMzE0M30.pWgkGatNxckQMtiUHo6NQOvk3QLiVAvjjCsOD43VpnE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);